#!/usr/bin/env bash
#
# combines PGL and Easylist fixed-domains into one dnsmasq config file that
# points any queries to 127.0.0.1
#
# scott@smemsh.net
# https://github.com/smemsh/utilmisc/
# https://spdx.org/licenses/GPL-2.0
#

easylist=https://easylist.to/easylist/easylist.txt

pgllist=https://pgl.yoyo.org/adservers/serverlist.php
pglparams="hostformat=nohtml&showintro=0&mimetype=plaintext"

sort \
<(curl -s $pgllist?"$pglparams") \
<(curl -s $easylist \
| grep '^||.*\^$' \
| grep -v / \
| sed -re 's,^..(.*).$,\1,'
) \
| uniq \
| while read domain
do echo "address=/$domain/127.0.0.1"
done
